### ISSUE TITLE
Custom Tracing - Service Name Options/Overrides

### ISSUE THREAD

**Issue by jgriepentrog** [dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation#34]
### Issue
Many services are being generated in Dynatrace when using the custom tracing feature, which creates clutter. It appears these services are generated with the name of the function/class due to the way the service name gets set from the `module_name` in the [custom decorator wrapper](https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/blob/master/autodynatrace/wrappers/custom/wrapper.py).

### Expectation
Custom tracing information is consolidated under a parent service name. E.g. if using Flask to have a web API named MyAPI, all of the tracing information would be under the MyAPI service vs broken out into multiple services.

### Example
```
import autodynatrace
from flask import Flask
app = Flask(__name__)

@autodynatrace.trace()
def foo():
    return "foo"

@autodynatrace.trace()
def bar():
    return "bar"

@app.route('/')
def hello_world():
    result = foo()
    result2 = bar()
    return f"Hello, {result}{result2}"
```
Currently, this will make three services - one for the flask application and one for each function rather than one service with enhanced tracing information in PurePaths.

### Proposal
The ability to provide an override at the service name into the wrapped `sdk.trace_custom_service()` call so that the same service name can be used.

### Potential Solutions
1. Environment variable(s) provide the override
    a. A new environment variable called `AUTODYNATRACE_SERVICE_NAME`
    b. Use `AUTODYNATRACE_APPLICATION_ID` as the override - either if set alone or in concert with another environment variable to toggle the override
2. Allow the decorator to accept an override, e.g. `autodynatrace.trace(service_name="foo")`

Would love feedback and please let me know any questions. Happy to clarify in any way that I can. Appreciate any time spent reviewing this issue!

**Comment by dlopes7** [comment]
Thanks for the report @jgriepentrog 

The behavior for 

```
@autodynatrace.trace
def foo():
    return "foo"

@autodynatrace.trace
def bar():
    return "bar"
```

Is actually a bug, both cases should give us a single service, with the module name as the service name (the methods are "requests" inside the service). But I see that this was broken by https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation/commit/1527f44f2a0a39fafbb1312134fd90b621e92587 

I agree that it would be nice to be able to overwrite the service name anyways, and I think having both the environment variable, but named `AUTODYNATRACE_CUSTOM_SERVICE_NAME` and an optional parameter to `@autodynatrace.trace` would be ideal, so the user can chose which one to use, the parameter allowing it to be a local setting instead of a global one.

I'll also attempt to revert the module name behavior for those simple methods, using the method name as the service is definitely not intended

**Comment by jgriepentrog** [comment]
Thanks David! What you've outlined sounds great. Appreciate the quick reply and efforts to continue to improve this module!

**Comment by jgriepentrog** [comment]
Hey David - apologies for the late reply. Wanted to let you know that the custom tracing service naming improvements are working great. Thanks again for the quick response!
